development:
  AWS_ACCESS_KEY_ID: AKIAJN6OII6BKTSRCJQA
  AWS_SECRET_ACCESS_KEY: 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

test:
  AWS_ACCESS_KEY_ID: AKIAJN6OII6BKTSRCJQA
  AWS_SECRET_ACCESS_KEY: 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

production:
  AWS_ACCESS_KEY_ID: AKIAJN6OII6BKTSRCJQA
  AWS_SECRET_ACCESS_KEY: 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
#
# development:
#   access_key_id: ENV['AWS_ACCESS_KEY_ID']
#   secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
#
# test:
#   access_key_id: ENV['AWS_ACCESS_KEY_ID']
#   secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
#
# production:
#   access_key_id: ENV['AWS_ACCESS_KEY_ID']
#   secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
